### ISSUE TITLE
Could not compile huffman

### ISSUE THREAD

**Issue by JustinHadi** [antoyo/uncbv#2]
Leaving stack trace
   Compiling huffman v0.0.2
     Running `rustc .cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs --crate-name huffman --crate-type lib -C opt-level=3 -C metadata=228b0f641cc7ae57 -C extra-filename=-228b0f641cc7ae57 --out-dir /home/squirrel/target-install/release/deps --emit=dep-info,link -L dependency=/home/squirrel/target-install/release/deps -L dependency=/home/squirrel/target-install/release/deps --extern bitreader=/home/squirrel/target-install/release/deps/libbitreader-9b3eae1a1b30e829.rlib --cap-lints allow`
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:47:27: 47:31 error: unresolved name `node` [E0425]
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:47         let $dir: &Tree = node.$dir.as_ref().unwrap();
                                                                                                      ^~~~
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111:13: 111:55 note: in this expansion of visit! (defined in .cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs)
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:47:27: 47:31 help: run `rustc --explain E0425` to see a detailed explanation
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111:48: 111:53 error: unresolved name `right` [E0425]
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111             visit!(current_node, tree, result, right);
                                                                                                                            ^~~~~
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111:13: 111:55 note: in this expansion of visit! (defined in .cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs)
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111:48: 111:53 help: run `rustc --explain E0425` to see a detailed explanation
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111:48: 111:53 error: unresolved name `right` [E0425]
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111             visit!(current_node, tree, result, right);
                                                                                                                            ^~~~~
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111:13: 111:55 note: in this expansion of visit! (defined in .cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs)
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111:48: 111:53 help: run `rustc --explain E0425` to see a detailed explanation
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:47:27: 47:31 error: unresolved name `node` [E0425]
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:47         let $dir: &Tree = node.$dir.as_ref().unwrap();
                                                                                                      ^~~~
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114:13: 114:54 note: in this expansion of visit! (defined in .cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs)
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:47:27: 47:31 help: run `rustc --explain E0425` to see a detailed explanation
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114:48: 114:52 error: unresolved name `left` [E0425]
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114             visit!(current_node, tree, result, left);
                                                                                                                            ^~~~
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114:13: 114:54 note: in this expansion of visit! (defined in .cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs)
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114:48: 114:52 help: run `rustc --explain E0425` to see a detailed explanation
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114:48: 114:52 error: unresolved name `left` [E0425]
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114             visit!(current_node, tree, result, left);
                                                                                                                            ^~~~
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114:13: 114:54 note: in this expansion of visit! (defined in .cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs)
.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114:48: 114:52 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to 6 previous errors

**Comment by antoyo** [comment]
Which Rust version do you have (`rustc -V`)?

Which command did you run?
On which platform?

I cannot reproduce this issue with both Rust stable (1.14) and nightly on ArchLinux.

Thanks for reporting this issue.

**Comment by JustinHadi** [comment]
rustc 1.7.0
cargo install uncbv
Ubuntu 16.04.1 LTS

**Comment by JustinHadi** [comment]
Apologies command was cargo install --path . ,other command produces another error which I will post below.

**Comment by JustinHadi** [comment]
rustc 1.7.0
cargo install uncbv
Ubuntu 16.04.1 LTS

 Compiling memchr v0.1.11
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:47:27: 47:31 error: unresolved name `node` [E0425]
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:47         let $dir: &Tree = node.$dir.as_ref().unwrap();
                                                                                                                     ^~~~
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111:13: 111:55 note: in this expansion of visit! (defined in /home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs)
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:47:27: 47:31 help: run `rustc --explain E0425` to see a detailed explanation
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111:48: 111:53 error: unresolved name `right` [E0425]
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111             visit!(current_node, tree, result, right);
                                                                                                                                           ^~~~~
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111:13: 111:55 note: in this expansion of visit! (defined in /home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs)
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111:48: 111:53 help: run `rustc --explain E0425` to see a detailed explanation
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111:48: 111:53 error: unresolved name `right` [E0425]
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111             visit!(current_node, tree, result, right);
                                                                                                                                           ^~~~~
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111:13: 111:55 note: in this expansion of visit! (defined in /home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs)
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:111:48: 111:53 help: run `rustc --explain E0425` to see a detailed explanation
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:47:27: 47:31 error: unresolved name `node` [E0425]
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:47         let $dir: &Tree = node.$dir.as_ref().unwrap();
                                                                                                                     ^~~~
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114:13: 114:54 note: in this expansion of visit! (defined in /home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs)
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:47:27: 47:31 help: run `rustc --explain E0425` to see a detailed explanation
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114:48: 114:52 error: unresolved name `left` [E0425]
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114             visit!(current_node, tree, result, left);
                                                                                                                                           ^~~~
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114:13: 114:54 note: in this expansion of visit! (defined in /home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs)
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114:48: 114:52 help: run `rustc --explain E0425` to see a detailed explanation
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114:48: 114:52 error: unresolved name `left` [E0425]
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114             visit!(current_node, tree, result, left);
                                                                                                                                           ^~~~
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114:13: 114:54 note: in this expansion of visit! (defined in /home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs)
/home/squirrel/.cargo/registry/src/github.com-88ac128001ac3a9a/huffman-0.0.2/src/lib.rs:114:48: 114:52 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to 6 previous errors
Build failed, waiting for other jobs to finish...
failed to compile `uncbv v0.2.2`, intermediate artifacts can be found at `/home/squirrel/uncbv/target-install`

**Comment by antoyo** [comment]
This is a very old version, but I made the changes to make it work on it.
Please tell me if `cargo install uncbv` now works.

**Comment by JustinHadi** [comment]
All works now!
