### ISSUE TITLE
Strange error at the conversion of the cbh into si4 

### ISSUE THREAD

**Issue by MisesEnForce** [antoyo/uncbv#4]
I am using a setup

- windows laptop + chessbase + official bases
- android phone with scid on the go and si4 bases

so that your uncbv tool helped me many times converting a cbv to cbh (and stuff), really great job !

Once I have the base in cbh (and stuff) format I then pass the whole thing to a virtual Ubuntu machne with scidb on it, and use scidb to convert the cbh format base to the si4 format (as no windows tool does the latter conversion, as far that I know.)

And it is the first time that I had failed conversion at the latter step. (Had this yesterday with the Mega Database 2022 from ChessBase.) So that there are three possibilities :

1.  The MegaDatabase in the native chessbase format or its ChessBase conversion to cbv has an issue/the native formats evolved in a way that the obtained cbv will failed to be converted in the next step
2.  There's an issue with the cbh converted with your uncbv tool (perhaps because of an evolution of the native chessbase fomat)
3.  There's an issue with scidb at the cbh to si4 conversion

As far as I was able to humanly check it's not 1, and I don't believe it's 2 either, so that I am rather banking on 3 (as scid hasn't been updated since 2018 and had an history of bugs, especially because of Tcl)

But I would nevertheless like to be sure. I naturally didn't have any error at step 2, but I don't see any log activation option in the available options. Would it be possible for me to update the cbv base somewhere so that you could test if your tool has an issue at the conversion ?

**Comment by antoyo** [comment]
Scidb is known to have issues with the mega database in general.
Usually, it shows a log of errors and skip the games it cannot open.

uncbv will print an errors if there's one and if there was a bug, it should just panic.
There's also the possibility of undefined behavior (by reading the code, I noticed it's unsafe in some places) which could be the issue we see here.

I'll try it on this database, though.

**Comment by antoyo** [comment]
You can upload the database somewhere and send the link to my email.

**Comment by MisesEnForce** [comment]
> Scidb is known to have issues with the mega database in general. Usually, it shows a log of errors and skip the games it cannot open.
> 
> uncbv will print an errors if there's one and if there was a bug, it should just panic. There's also the possibility of undefined behavior (by reading the code, I noticed it's unsafe in some places) which could be the issue we see here.
> 
> I'll try it on this database, though.

In fact yes, I know that frequentely games are skipped for many reasons, all of skipped games being log at the end, but in my case it was a vile crash starting with :
![image](https://user-images.githubusercontent.com/5349602/144721708-e20582f3-aab0-4c78-8696-0de5c0cae037.png)
cliking on "ok" lend to : 
![image](https://user-images.githubusercontent.com/5349602/144721730-40e8bfef-4a0d-40d3-b7cd-373bf8455958.png)
and asking for details yielded : 
![image](https://user-images.githubusercontent.com/5349602/144721744-d01d59b8-fc33-4493-82ee-86e7784856da.png)
Thx for trying, it is really nice to help. (I dabbled into scid years ago but never succeed in hooking up with the aim of understading the code, at least the internal conversions parts.)

**Comment by MisesEnForce** [comment]
> You can upload the database somewhere and send the link to my email.

Will do

**Comment by MisesEnForce** [comment]
> You can upload the database somewhere and send the link to my email.

Mail sent to your zoho address.

**Comment by MisesEnForce** [comment]
> Scidb is known to have issues with the mega database in general. Usually, it shows a log of errors and skip the games it cannot open.
> 
> uncbv will print an errors if there's one and if there was a bug, it should just panic. There's also the possibility of undefined behavior (by reading the code, I noticed it's unsafe in some places) which could be the issue we see here.
> 
> I'll try it on this database, though.

Actually I was fed up with having to do this with scidb on linux on a virtual machine, so that I built scid with WSL (Windows subsystem for linux), which also build the command line "cbh2si4" executable that scidb's GUI uses for the conversion and used this executable for the conversion. The conversion was done without any crash (but as usual a few 503 games were rejected.)

Now that I have this cmd line executable, I don't need scidb at all anymore. ;)

**Comment by antoyo** [comment]
Does that mean that we can close this issue as it does not seem to be a `uncbv` issue?

**Comment by MisesEnForce** [comment]
> Does that mean that we can close this issue as it does not seem to be a `uncbv` issue?

Indeed, I forgot to say it.
